name: is_it_safe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_svg: ^1.1.4
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  intl_utils: ^2.4.1
  jwt_decode: ^0.3.1
  logger: ^1.1.0
  lottie: ^1.4.3
  mask_text_input_formatter: ^2.0.0
  meta: ^1.7.0
  mocktail: ^0.3.0
  platform: ^3.1.0
  plugin_platform_interface: ^2.1.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  simple_animations: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  modular_test: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/logo/logo.png
    - images/
    - images/modules/
    - images/modules/auth/
    - images/modules/auth/
    - images/modules/auth/profile_pictures/
    - images/modules/auth/profile_pictures/placeholder/
    - images/modules/home/
    - images/modules/core/empty/
    - images/modules/core/icons/
    - images/modules/core/placeholder/
    - images/modules/review/

flutter_intl:
  enabled: true
  main_locale: pt
