name: is_it_safe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  #Funcionalidades do Sistema
  flutter_modular: ^4.1.2
  provider: ^6.0.1
  plugin_platform_interface: ^2.0.2
  platform: ^3.1.0
  build_runner: ^2.1.10
  logger: ^1.1.0
  meta: ^1.7.0

  #Requisições HTTP
  dio: ^4.0.0

  #Internacionalização
  intl_utils: ^2.4.1

  #Estilização
  google_fonts: ^2.3.1
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  mask_text_input_formatter: ^2.0.0

  #Componentes
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^0.22.0
  simple_animations: ^4.0.1

  #Armazenamento
  shared_preferences: ^2.0.8

  #Testes
  mocktail: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  modular_test: ^1.0.1+1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/modules/
    - images/modules/auth/
    - images/app/profile_pictures/
    - images/app/on_boarding/
    - images/app/profile_pictures/
    - images/app/home/
    - images/app/home/drawer/
    - images/app/profile_pictures/placeholder/
    - images/icons/
    - images/app/search_pictures/placeholder/
    - test/src/service/api/modules/auth/mocks/
    

flutter_intl:
  enabled: true
  main_locale: pt