name: Flutter CI/CD

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          # Use the latest Flutter version available
          flutter-version: 3.7.8

      # Install dependencies
      - name: Get dependencies
        run: flutter pub get

      # Run tests
      - name: Run tests
        run: flutter test
